import type { Metadata } from "next";
import { Inter as FontSans } from "next/font/google";
import "./globals.css";
import "@radix-ui/themes/styles.css";
import { cn } from "@/lib/utils";
import { Flex, Separator, Theme } from "@radix-ui/themes";
import Sidebar from "@/components/Sidebar";
import { Toaster } from "@/components/ui/toaster";

export const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          "min-h-screen bg-background font-sans antialiased",
          fontSans.variable
        )}
      >
        <Theme accentColor="purple" grayColor="sand" radius="large">
          <Flex className="min-h-screen bg-background font-sans antialiased">
            <Sidebar />
            <Flex direction="column">
              <Separator orientation="vertical" size="4" />
            </Flex>
            {children}
          </Flex>
          <Toaster />
        </Theme>
      </body>
    </html>
  );
}
